### ISSUE TITLE
What page had the issue?

### ISSUE THREAD

**Issue by luke-holloway** [jadilorenzo/testy#8]
Trying to find what page has the issue you showed me. I got the app up and running. Can you post a link? @jadilorenzo

**Comment by jadilorenzo** [comment]
Oh, it was fixed. The material container was thrown off by the animation. It would be awesome if you could take a look at the pull request though.

**Comment by luke-holloway** [comment]
@jadilorenzo Oh okay! Good work. I'll check the PR sometime today.
